[tool.poetry]
name = "ht_27"
version = "0.1.0"
description = ""
authors = ["Danil Galkin <pixell_tm@bk.ru>"]

[tool.poetry.dependencies]
python = "^3.8"
Django = "3.*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
